fileManager:
  folder: .\
  timestamp: true
  force: true
  append: false
  files:
    - name: results
      type: excel
      root: TabulatedResults
      extension: xlsx
    - name: journal
      type: word
      root: OngoingWorkJournal
      extension: docx
      force: false
      append: true
